### ISSUE TITLE
video thumbnail job failed 

### ISSUE THREAD

**Issue by umarhadi** [pixelfed/support#157]
when i upload a `.mp4` video, video thumbnail change to "no preview available".

![image](https://user-images.githubusercontent.com/31447862/168654721-aa3bc595-e209-412b-9f84-5c73fa62cce2.png)

and i'm check on horizon, `App\Jobs\VideoPipeline\VideoThumbnail` it's failed.

![image](https://user-images.githubusercontent.com/31447862/168656146-b404c0bb-bf29-434d-add4-7f68d4069f3b.png)

here's the stack trace:

```
Exception

UnexpectedValueException: The stream or file "/var/www/pixelfed/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied in /var/www/pixelfed/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:146
--
Stack trace:
#0 /var/www/pixelfed/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(48): Monolog\Handler\StreamHandler->write()
pixelfed/pixelfed#1 /var/www/pixelfed/vendor/monolog/monolog/src/Monolog/Logger.php(327): Monolog\Handler\AbstractProcessingHandler->handle()
pixelfed/pixelfed#2 /var/www/pixelfed/vendor/monolog/monolog/src/Monolog/Logger.php(526): Monolog\Logger->addRecord()
pixelfed/pixelfed#3 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Log/Logger.php(183): Monolog\Logger->info()
pixelfed/pixelfed#4 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Log/Logger.php(130): Illuminate\Log\Logger->writeLog()
pixelfed/pixelfed#5 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(624): Illuminate\Log\Logger->info()
pixelfed/pixelfed#6 /var/www/pixelfed/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php(60): Illuminate\Log\LogManager->info()
pixelfed/pixelfed#7 /var/www/pixelfed/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(207): Alchemy\BinaryDriver\ProcessRunner->run()
pixelfed/pixelfed#8 /var/www/pixelfed/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(136): Alchemy\BinaryDriver\AbstractBinary->run()
pixelfed/pixelfed#9 /var/www/pixelfed/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe/OptionsTester.php(61): Alchemy\BinaryDriver\AbstractBinary->command()
pixelfed/pixelfed#10 /var/www/pixelfed/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe/OptionsTester.php(43): FFMpeg\FFProbe\OptionsTester->retrieveHelpOutput()
pixelfed/pixelfed#11 /var/www/pixelfed/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php(237): FFMpeg\FFProbe\OptionsTester->has()
pixelfed/pixelfed#12 /var/www/pixelfed/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php(206): FFMpeg\FFProbe->probe()
pixelfed/pixelfed#13 /var/www/pixelfed/vendor/pbmedia/laravel-ffmpeg/src/FFMpeg/FFProbe.php(70): FFMpeg\FFProbe->streams()
pixelfed/pixelfed#14 /var/www/pixelfed/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFMpeg.php(95): ProtoneMedia\LaravelFFMpeg\FFMpeg\FFProbe->streams()
pixelfed/pixelfed#15 /var/www/pixelfed/vendor/pbmedia/laravel-ffmpeg/src/Drivers/PHPFFMpeg.php(124): FFMpeg\FFMpeg->open()
pixelfed/pixelfed#16 /var/www/pixelfed/vendor/pbmedia/laravel-ffmpeg/src/MediaOpener.php(135): ProtoneMedia\LaravelFFMpeg\Drivers\PHPFFMpeg->open()
pixelfed/pixelfed#17 /var/www/pixelfed/vendor/pbmedia/laravel-ffmpeg/src/MediaOpener.php(174): ProtoneMedia\LaravelFFMpeg\MediaOpener->getDriver()
pixelfed/pixelfed#18 /var/www/pixelfed/app/Jobs/VideoPipeline/VideoThumbnail.php(56): ProtoneMedia\LaravelFFMpeg\MediaOpener->export()
pixelfed/pixelfed#19 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Jobs\VideoPipeline\VideoThumbnail->handle()
pixelfed/pixelfed#20 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
pixelfed/pixelfed#21 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
pixelfed/pixelfed#22 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
pixelfed/pixelfed#23 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\BoundMethod::call()
pixelfed/pixelfed#24 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call()
pixelfed/pixelfed#25 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
pixelfed/pixelfed#26 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
pixelfed/pixelfed#27 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
pixelfed/pixelfed#28 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(120): Illuminate\Bus\Dispatcher->dispatchNow()
pixelfed/pixelfed#29 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
pixelfed/pixelfed#30 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
pixelfed/pixelfed#31 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\Pipeline\Pipeline->then()
pixelfed/pixelfed#32 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
pixelfed/pixelfed#33 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()
pixelfed/pixelfed#34 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(428): Illuminate\Queue\Jobs\Job->fire()
pixelfed/pixelfed#35 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(378): Illuminate\Queue\Worker->process()
pixelfed/pixelfed#36 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(172): Illuminate\Queue\Worker->runJob()
pixelfed/pixelfed#37 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(117): Illuminate\Queue\Worker->daemon()
pixelfed/pixelfed#38 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Console\WorkCommand->runWorker()
pixelfed/pixelfed#39 /var/www/pixelfed/vendor/laravel/horizon/src/Console/WorkCommand.php(51): Illuminate\Queue\Console\WorkCommand->handle()
pixelfed/pixelfed#40 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Horizon\Console\WorkCommand->handle()
pixelfed/ideas#1 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
pixelfed/pixelfed#42 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
pixelfed/pixelfed#43 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
pixelfed/pixelfed#44 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\BoundMethod::call()
pixelfed/pixelfed#45 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
pixelfed/pixelfed#46 /var/www/pixelfed/vendor/symfony/console/Command/Command.php(298): Illuminate\Console\Command->execute()
pixelfed/pixelfed#47 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
pixelfed/pixelfed#48 /var/www/pixelfed/vendor/symfony/console/Application.php(1005): Illuminate\Console\Command->run()
pixelfed/pixelfed#49 /var/www/pixelfed/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
pixelfed/pixelfed#50 /var/www/pixelfed/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
pixelfed/pixelfed#51 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\Component\Console\Application->run()
pixelfed/pixelfed#52 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
pixelfed/pixelfed#53 /var/www/pixelfed/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
pixelfed/pixelfed#54 {main}

```

**Comment by zealov** [comment]
安装FFMpeg 扩展 并配置好路径

**Comment by dansup** [comment]
This looks like a permission issue! If you are still experiencing this, feel free to re-open.

**Comment by antondomratchev** [comment]
Does anyone know which user is executing the `ffmpeg` command to generate the thumbnail? All the permission in those directories are looking correct. 
```
-rw-r--r--  1 www-data www-data 89793786 May  4 22:27 Yv7ZfSuBaMy1XXPaWqVvEluhg0APidfVZG74pR2a.mp4
```

**Comment by antondomratchev** [comment]
@dansup Do you happen to know if i need to change user or group of ffmpeg? I added a write permission to the group as well.
