### ISSUE TITLE
Route [timeline.personal] not defined

### ISSUE THREAD

**Issue by TiMESPLiNTER** [pixelfed/support#65]
Pixelfed v0.10.7
PHP 7.4

When I want to visit the root path (/) of the application I get the following exception:

```
PHP message: PHP Fatal error: Uncaught Symfony\Component\Routing\Exception\RouteNotFoundException: Route [timeline.personal] not defined. in /usr/share/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:420
Stack trace:
#0 /usr/share/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(782): Illuminate\Routing\UrlGenerator->route('timeline.person...', Array, true)
#1 /usr/share/pixelfed/storage/framework/views/d933f9d7ea6e7c0018077588b0cef445acd13d25.php(3): route('timeline.person...')
#2 /usr/share/pixelfed/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(43): include('/usr/share/pixe...')
#3 /usr/share/pixelfed/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('/usr/share/pixe...', Array)
#4 /usr/share/pixelfed/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(36): Illuminate\View\Engines\CompilerEn
```

I already tried multiple times to clear the cache and cache the routes.

```
sudo -u www-data php artisan cache:clear
sudo -u www-data php artisan route:cache
```

I then changed to debug mode and env "dev" and get the following error in the browser:

```
ErrorException
Erroneous data format for unserializing 'Symfony\Component\Routing\CompiledRoute' 
```

I followed these instructions: https://docs.pixelfed.org/installing-pixelfed/installation.html#download-source-via-git (plus checking out tag v0.10.7 in addition)

**Comment by TiMESPLiNTER** [comment]
Okay I just found out the issue. The CLI PHP version was 7.4 whereas the PHP-FPM version was 7.3. That doesn't work. So for anybody ending up on that issue: make sure you use the same PHP version for FPM and CLI.
