### ISSUE TITLE
federates to pixelfed.social, does not federate to mastodon

### ISSUE THREAD

**Issue by norayr** [pixelfed/support#85]
hello, pixelfed.social streams are federated to my mastodon instance normally.

however my newly installed pixelfed instance's posts are not federated to mastodon. but are federated to pixelfed.social.

i watched logs of my mastodon instance and sidekiq says:

```
Rejected Create activity https://xn--49ap3c.xn--y9a3aq/p/norayr/155091301820403712/activity from https://xn--49ap3c.xn--y9a3aq/users/norayr
```

while puma says:
```
[620275dc-6fc4-42e8-b6ab-5e919598b2b9] method=POST path=/inbox format=json controller=ActivityPub::InboxesController action=create status=202 duration=3.20 view=0.00 db=0.38 key=https://xn--49ap3c.xn--y9a3aq/users/norayr#main-key
```

the error i found in my installation as that i put random string to APP_KEY instead of generating it with special command. now this is solved and i have a correct and generated APP_KEY.
i made cache again and restarted pixelfed services that i have running:

```
 php artisan horizon
```
and
```
php artisan queue:work
```

other problem i have is that previews are not generated.

thanks.

**Comment by dansup** [comment]
@norayr Sounds like it may be an issue with your mastodon instance if your pixelfed posts federate to pixelfed.social fine.

**Comment by norayr** [comment]
my mastodon federates with many many many other mastodons fine.

what about previews? i cannot get them generated. i don't know if this is related but when uploading an image i see lines

```
[2020-04-13 15:25:57][62] Processing: App\Jobs\ImageOptimizePipeline\ImageResize
[2020-04-13 15:25:57][62] Processing: App\Jobs\ImageOptimizePipeline\ImageResize
[2020-04-13 15:25:57][62] Processing: App\Jobs\ImageOptimizePipeline\ImageResize
[2020-04-13 15:25:58][62] Failed:     App\Jobs\ImageOptimizePipeline\ImageResize
```

but i have all the deps installed i think.

**Comment by norayr** [comment]
very interesting.

today I have updated pixelfed, and now it federates to my mastodon instance, but doesn't federate to pixelfed.social. (:

**Comment by norayr** [comment]
here i uploaded new image, and it looks like i have no errors, but pixelfed.social doesn't see it

```
[2020-06-23 20:24:19][35] Processing: App\Jobs\ImageOptimizePipeline\ImageOptimize
[2020-06-23 20:24:19][35] Processed:  App\Jobs\ImageOptimizePipeline\ImageOptimize
[2020-06-23 20:24:19][36] Processing: App\Jobs\ImageOptimizePipeline\ImageResize
[2020-06-23 20:24:19][36] Processing: App\Jobs\ImageOptimizePipeline\ImageResize
[2020-06-23 20:24:20][36] Processing: App\Jobs\ImageOptimizePipeline\ImageResize
[2020-06-23 20:24:20][36] Failed:     App\Jobs\ImageOptimizePipeline\ImageResize
[2020-06-23 20:24:31][37] Processing: App\Jobs\StatusPipeline\NewStatusPipeline
[2020-06-23 20:24:31][37] Processed:  App\Jobs\StatusPipeline\NewStatusPipeline
[2020-06-23 20:24:31][38] Processing: App\Jobs\StatusPipeline\StatusEntityLexer
[2020-06-23 20:24:31][38] Processed:  App\Jobs\StatusPipeline\StatusEntityLexer
[2020-06-23 20:24:31][39] Processing: App\Jobs\StatusPipeline\StatusActivityPubDeliver
[2020-06-23 20:24:32][39] Processed:  App\Jobs\StatusPipeline\StatusActivityPubDeliver
```

**Comment by norayr** [comment]
does 2 deliver process means it got delivered to 2 instances?

**Comment by norayr** [comment]
but it is able to federate to pixelfed.de

**Comment by norayr** [comment]
ok somehow federation problems seems solved.

now, on resizing:

```
Illuminate\Queue\MaxAttemptsExceededException: App\Jobs\ImageOptimizePipeline\ImageResize has been attempted too many times or run too long. The job may have previously timed out. in /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:649
Stack trace:
#0 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(436): Illuminate\Queue\Worker->maxAttemptsExceededException(Object(Illuminate\Queue\Jobs\RedisJob))
#1 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(346): Illuminate\Queue\Worker->markJobAsFailedIfAlreadyExceedsMaxAttempts('redis', Object(Illuminate\Queue\Jobs\RedisJob), 1)
#2 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(306): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#3 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(132): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#4 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\Queue\Worker->daemon('redis', 'default', Object(Illuminate\Queue\WorkerOptions))
#5 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'default')
#6 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#7 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array(Array, Array)
#8 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#9 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#10 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#11 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#12 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call(Array)
#13 /home/pixelfed/vendor/symfony/console/Command/Command.php(258): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#14 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#15 /home/pixelfed/vendor/symfony/console/Application.php(911): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /home/pixelfed/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /home/pixelfed/vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /home/pixelfed/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 {main}
```

which tool should i have for resizing it?

i have dev-php/pecl-imagick-3.4.4 on my gentoo for my php-7.3

**Comment by norayr** [comment]
and php is compiled with exif flag.

looks like this is some log of resize i found:
payload:

```
{"pushedAt":"1593280822.7971","id":"14","displayName":"App\\Jobs\\ImageOptimizePipeline\\ImageResize","maxTries":null,"timeout":null,"uuid":"6a122898-e6cf-4e61-a544-ea96f340cc93","attempts":2,"maxExceptions":null,"data":{"commandName":"App\\Jobs\\ImageOptimizePipeline\\ImageResize","command":"O:42:\"App\\Jobs\\ImageOptimizePipeline\\ImageResize\":10:{s:8:\"\u0000*\u0000media\";O:45:\"Illuminate\\Contracts\\Database\\ModelIdentifier\":4:{s:5:\"class\";s:9:\"App\\Media\";s:2:\"id\";i:111;s:9:\"relations\";a:0:{}s:10:\"connection\";s:5:\"pgsql\";}s:23:\"deleteWhenMissingModels\";b:1;s:3:\"job\";N;s:10:\"connection\";N;s:5:\"queue\";N;s:15:\"chainConnection\";N;s:10:\"chainQueue\";N;s:5:\"delay\";N;s:10:\"middleware\";a:0:{}s:7:\"chained\";a:0:{}}"},"delay":null,"job":"Illuminate\\Queue\\CallQueuedHandler@call","timeoutAt":null,"tags":["App\\Media:111"],"type":"job"}
```
exception:
```
Intervention\Image\Exception\NotWritableException: Can't write image data to path (/home/pixelfed/storage/app/public/m/0435cc59bc9edaf1bf37a87430b321de710d4cdf/84768b09ed0178572707bce74f1002a714714a2d/GCcA2ceJburBBKbk9sxwNObFgioA6bZjlfyyQx9b.jpeg) in /home/pixelfed/vendor/intervention/image/src/Intervention/Image/Image.php:150
Stack trace:
#0 /home/pixelfed/app/Util/Media/Image.php(167): Intervention\Image\Image->save()
#1 /home/pixelfed/app/Util/Media/Image.php(93): App\Util\Media\Image->handleImageTransform()
#2 /home/pixelfed/app/Util/Media/Image.php(81): App\Util\Media\Image->handleResizeImage()
#3 /home/pixelfed/app/Jobs/ImageOptimizePipeline/ImageResize.php(54): App\Util\Media\Image->resizeImage()
#4 [internal function]: App\Jobs\ImageOptimizePipeline\ImageResize->handle()
#5 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array()
#6 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#7 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\Container\Util::unwrapIfClosure()
#8 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#9 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\Container\BoundMethod::call()
#10 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call()
#11 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#12 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#13 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then()
#14 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\Bus\Dispatcher->dispatchNow()
#15 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#16 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#17 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\Pipeline\Pipeline->then()
#18 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#19 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()
#20 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\Queue\Jobs\Job->fire()
#21 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(306): Illuminate\Queue\Worker->process()
#22 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(132): Illuminate\Queue\Worker->runJob()
#23 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\Queue\Worker->daemon()
#24 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\Queue\Console\WorkCommand->runWorker()
#25 /home/pixelfed/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\Queue\Console\WorkCommand->handle()
#26 [internal function]: Laravel\Horizon\Console\WorkCommand->handle()
#27 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array()
#28 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#29 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\Container\Util::unwrapIfClosure()
#30 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#31 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\Container\BoundMethod::call()
#32 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call()
#33 /home/pixelfed/vendor/symfony/console/Command/Command.php(258): Illuminate\Console\Command->execute()
#34 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#35 /home/pixelfed/vendor/symfony/console/Application.php(911): Illuminate\Console\Command->run()
#36 /home/pixelfed/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand()
#37 /home/pixelfed/vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun()
#38 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run()
#39 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#40 /home/pixelfed/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#41 {main}
```

**Comment by norayr** [comment]
i see that looks like a permission problem, but i tried so many combinations of chmod/chown, and official manual doesn't list who should be the owner and group of which directory.

**Comment by norayr** [comment]
right now i can delete files without anything wrong in the output so i think the permissions is not bad.

**Comment by norayr** [comment]
right now i uploaded the image, and i have

```
[2020-06-27 21:47:36][3] Processing: App\Jobs\ImageOptimizePipeline\ImageOptimize
[2020-06-27 21:47:36][3] Processed:  App\Jobs\ImageOptimizePipeline\ImageOptimize
[2020-06-27 21:47:36][4] Processing: App\Jobs\ImageOptimizePipeline\ImageResize
[2020-06-27 21:47:36][4] Processing: App\Jobs\ImageOptimizePipeline\ImageResize
[2020-06-27 21:47:36][4] Processing: App\Jobs\ImageOptimizePipeline\ImageResize
[2020-06-27 21:47:36][4] Failed:     App\Jobs\ImageOptimizePipeline\ImageResize
```

then in postgre failed_jobs table the last row is

payload:
```
{"uuid":"462e49a1-721a-44e8-b95b-7c3c2c86289f","displayName":"App\\Jobs\\LikePipeline\\LikePipeline","job":"Illuminate\\Queue\\CallQueuedHandler@call","maxTries":1,"maxExceptions":null,"delay":null,"timeout":5,"timeoutAt":null,"data":{"commandName":"App\\Jobs\\LikePipeline\\LikePipeline","command":"O:34:\"App\\Jobs\\LikePipeline\\LikePipeline\":12:{s:7:\"\u0000*\u0000like\";O:45:\"Illuminate\\Contracts\\Database\\ModelIdentifier\":4:{s:5:\"class\";s:8:\"App\\Like\";s:2:\"id\";i:21;s:9:\"relations\";a:0:{}s:10:\"connection\";s:5:\"pgsql\";}s:23:\"deleteWhenMissingModels\";b:1;s:7:\"timeout\";i:5;s:5:\"tries\";i:1;s:3:\"job\";N;s:10:\"connection\";N;s:5:\"queue\";N;s:15:\"chainConnection\";N;s:10:\"chainQueue\";N;s:5:\"delay\";N;s:10:\"middleware\";a:0:{}s:7:\"chained\";a:0:{}}"},"id":"37","attempts":0,"type":"job","tags":["App\\Like:21"],"pushedAt":"1593284262.3334"}
```

exception:
```
Illuminate\Queue\MaxAttemptsExceededException: App\Jobs\LikePipeline\LikePipeline has been attempted too many times or run too long. The job may have previously timed out. in /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:649
Stack trace:
#0 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(163): Illuminate\Queue\Worker->maxAttemptsExceededException(Object(Illuminate\Queue\Jobs\RedisJob))
#1 /home/pixelfed/app/Services/ActivityPubDeliveryService.php(60): Illuminate\Queue\Worker->Illuminate\Queue\{closure}(14, Array)
#2 /home/pixelfed/app/Services/ActivityPubDeliveryService.php(41): App\Services\ActivityPubDeliveryService->queueDelivery()
#3 /home/pixelfed/app/Util/ActivityPub/Helpers.php(465): App\Services\ActivityPubDeliveryService->send()
#4 /home/pixelfed/app/Jobs/LikePipeline/LikePipeline.php(104): App\Util\ActivityPub\Helpers::sendSignedObject(Object(App\Profile), 'https://pixelfe...', Array)
#5 /home/pixelfed/app/Jobs/LikePipeline/LikePipeline.php(62): App\Jobs\LikePipeline\LikePipeline->remoteLikeDeliver()
#6 [internal function]: App\Jobs\LikePipeline\LikePipeline->handle()
#7 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array(Array, Array)
#8 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#9 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#10 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#11 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#12 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#13 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\LikePipeline\LikePipeline))
#14 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\LikePipeline\LikePipeline))
#15 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#16 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\LikePipeline\LikePipeline), false)
#17 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}(Object(App\Jobs\LikePipeline\LikePipeline))
#18 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\LikePipeline\LikePipeline))
#19 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#20 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\Queue\Jobs\RedisJob), Object(App\Jobs\LikePipeline\LikePipeline))
#21 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#22 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\Queue\Jobs\Job->fire()
#23 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(306): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#24 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(132): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#25 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\Queue\Worker->daemon('redis', 'default', Object(Illuminate\Queue\WorkerOptions))
#26 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'default')
#27 /home/pixelfed/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\Queue\Console\WorkCommand->handle()
#28 [internal function]: Laravel\Horizon\Console\WorkCommand->handle()
#29 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array(Array, Array)
#30 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#31 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#32 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#33 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#34 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call(Array)
#35 /home/pixelfed/vendor/symfony/console/Command/Command.php(258): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#36 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#37 /home/pixelfed/vendor/symfony/console/Application.php(911): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 /home/pixelfed/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#39 /home/pixelfed/vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#40 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#41 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#42 /home/pixelfed/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#43 {main}
```

this is something about timeout. but what does it do, how does it resize the image?

**Comment by norayr** [comment]
```
 $ php -i | grep imagick
Additional .ini files parsed => /etc/php/cli-php7.3/ext-active/imagick.ini,
imagick
imagick module => enabled
imagick module version => 3.4.4
imagick classes => Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator, ImagickKernel
imagick.locale_fix => 0 => 0
imagick.progress_monitor => 0 => 0
imagick.skip_version_check => 0 => 0
```

**Comment by norayr** [comment]
solved by adding

```
IMAGE_DRIVER=imagick
```
in .env

then

```
php artisan config:cache
php artisan cache:clear
php artisan media:optimize
```
